### PR TITLE
[feature] [UDL] adding UDL logic for hex, binary, octal

### PR DESCRIPTION
**Pull request by badair**
-0x1234_c now allowed (hex)
-0b01010_c now allowed (binary)
-0123_c now allowed (octal)

### CODE REVIEW

**Comment by ldionne** [comment]
Looks good. I don't have time to look at it in detail right now, but I'll give you feedback later today or tomorrow.

**Comment by badair** [comment]
2 case-sensitive tests added.

**Comment by badair** [comment]
Fixed whitespace.

**Comment by ldionne** [comment]
Rebased and merged manually. Thanks a lot @badair!

**Pull request closed without merging**
