### PR TITLE
[experimental] printable hana::template_

### PR DESCRIPTION
**Pull request by ricejasonf**
If you would like, I can do this for the other `Metafunctions` for consistency, but first I wanted to gauge your reaction to giving them their own tags.

I think this would be useful for more than just `Printable`.

### CODE REVIEW

**Comment by ricejasonf** [comment]
I made the suggested changes, but did not add any more implementaions. Perhaps the default should print the output from `boost::core::demangle`.

**Comment by ldionne** [comment]
Random note: It's crazy and scary to think that any comment we made on the original diff disappears when we update the diff. Not-so-good job from GitHub on this.

**Comment by ldionne** [comment]
Question: Why did you not implement it for other `Metafunction`s? Is it just a question of time, or is there any underlying issue that would prevent that?

**Comment by ricejasonf** [comment]
>Random note: It's crazy and scary to think that any comment we made on the original diff disappears when we update the diff. Not-so-good job from GitHub on this.

I'd bet the information is still there, but the revision is no longer displayed in the ui.

>Question: Why did you not implement it for other Metafunctions? Is it just a question of time, or is there any underlying issue that would prevent that?

Actually I'm going to try doing a specialization for all `hana::Metafunction`s.

**Comment by ricejasonf** [comment]
I tried implementing a `print_impl` with `when<hana::Metafunction<...>...`, but it was problematic getting it to match the variadic templates not to mention that `metafunction_class` has a different signature (ie it is not variadic).

I went ahead and added explicit specializations for each Metafunction and switched to using a **regex** to "prettyify" the output. If you don't want it pulling in `<regex>` I can change it back, but I think it is more robust this way.

**Comment by ldionne** [comment]
That seems good. I don't mind the `<regex>` include. Can you please squash those two commits and I'll merge the PR?

**Comment by ricejasonf** [comment]
I won't be getting to it immediately, but I would like to add Printable to the functions in Functional. Should merging be deferred and I add that here, or should I just do a new PR later?

**Comment by ldionne** [comment]
Why do you need to print the functions in Functional? Printing a function properly is impossible in the general case.. In all cases, that should be attempted in a different PR.

**Comment by ldionne** [comment]
Merged in 2b0ede886e922858e5c68b3732d52cbcad89a5c4.

**Comment by ricejasonf** [comment]
>Why do you need to print the functions in Functional?

In my case I have trees with types and templates in them. It is useful to be able to use something like `hana::partial` on the result of `hana::template_` in some cases. So maybe it would look like:
```
partial(template<nbdl::StoreEmitter>, type<std::unordered_map>)
```
where `nbdl::StoreEmitter` is a template taking two types.

My current workaround has been to wrap the whole works in `hana::type_c<...>`, because otherwise `print` explodes.

**Comment by ldionne** [comment]
Hmm. It would work fine when the function is a `template_`, but what about when the function is something arbitrary? For example, what would you expect `hana::experimental::print([]{})` to output?

**Comment by ricejasonf** [comment]
lol idk. I should probably play around with it and see what is feasible.

**Comment by ldionne** [comment]
Sure; don't hesitate to create another PR or an issue if you think this is a valuable addition, and we'll discuss. I'm just a bit skeptical, just as I would be if someone proposed to make functions `Comparable` (impossible in the general case). I'm not saying that printing functions is not feasible, but it certainly is not obvious how to do it sensibly.

**Pull request closed without merging**
