### PR TITLE
[map] Use an eager algorithm for map lookup

### PR DESCRIPTION
**Pull request by ricejasonf**
Related #223

### CODE REVIEW

**Comment by ricejasonf** [comment]
There may be more room for improvement. I'm not sure. After rebasing the benchmarks seemed to run .01-.02 seconds slower at n=400. 

Using the specialization for type_tag in `at_key` doesn't seem to make a difference so maybe I am doing something wrong there.

**Comment by ricejasonf** [comment]
On my box, `benchmark.at_key.lookup.compile` shows map compiling in 1.38s for every test. It also reveals that `hana::set` scales linearly.

**Comment by ricejasonf** [comment]
2911e959ffca7cda0dcac97e3b0f4823ce8308e2 removes some vestigal helpers I accidentally left in.

I tried having `make` create `map_impl` directly, but there was no noticeable performance difference.

**Comment by ricejasonf** [comment]
For `benchmark.at_key.lookup.compile`, I substituted a lightweight Product for the map which puts it on par with tuple and set. (0.5s on my box)

**Comment by ldionne** [comment]
OK, so I updated your branch with my modifications.

**Comment by ldionne** [comment]
This is superseded by #247, which shows better compile-time performance.

**Pull request closed without merging**
