### PR TITLE
[bug] convert predicate results to bool

### LINKED ISSUE #221: [find_if] Predicates should be allowed to return an int_c.
I wanted to use hana::length as a predicate for `find_if` and `filter`, but it does not compile. Consider the following example.
```
#include<boost/hana.hpp>

namespace hana = boost::hana;

int main()
{
  static_assert(hana::find_if(hana::make_tuple(
      hana::make_tuple(),
      hana::make_tuple(),
      hana::make_tuple(hana::int_c<0>, hana::int_c<1>),
      hana::make_tuple()), hana::length)
        ==
      hana::just(hana::make_tuple(hana::int_c<0>, hana::int_c<1>)), "");
}
```

### PR DESCRIPTION
**Pull request by ricejasonf**
Fixes #221

### CODE REVIEW

**Comment by ricejasonf** [comment]
I used `detail::decay` in partition.hpp because `Pred` was `const&`. I noticed in filter.hpp you use `Pred const& pred` with `pred` in the `decltype` which gets around that. Perhaps that is better idk

**Comment by ricejasonf** [comment]
I would like to know why `partition` was working inside `sort`, but not in my test case. (before I used `detail::decay`)

**Comment by ricejasonf** [comment]
because it was an lvalue?

**Comment by ricejasonf** [comment]
Oh, I think it is because the return value is actually and rvalue because `id` forwards it's return value.

**Comment by ldionne** [comment]
This looks good to me. Was there anything else you wanted to add to the PR?

**Comment by ricejasonf** [comment]
No, thank you.

**Comment by ricejasonf** [comment]
It says "boostorg:master". Can you change that?

**Comment by ldionne** [comment]
Oops, seems like you created a PR against master. I can't change that on GitHub, but I'm going to merge the PR manually anyway.

**Pull request closed without merging**
