### PR TITLE
Compiler detection for LLVM/Clang with Visual Studio integration

### PR DESCRIPTION
**Pull request by m-j-w**
Provided are some changes to the compiler detection with cmake.
The invocation on the command line (cmd.exe) actually only requires for a 32bit build
```
cmake .. -TLLVM-vs2014
```
A 64bit build is generated with
```
cmake .. -TLLVM-vs2014 -G"Visual Studio 14 2015 Win64"
```
Other options should not be required on a clean cmake run. The additional comparisons are for the case when the initial invocation is missing the -T argument, and hence everything get's really messy. This happens in particular when an existing solution is changed afterwards, e.g. by invoking cmake again with other options, but might also happen by other manual changes in the solution and the automatically triggered cmake run.

The check for MSVC must be the first. Otherwise the MSC compiler will fail at the first `#warning`. MSC uses a `#pragma message` for the same purpose.
The standard library of MSVC can be checked by the compiler version `_MSC_VER` since its bundled. However, detecting MSVC is not sufficient; `_clang_` must also be present. Unfortunately, also this might not be enough since the compiler could be changed manually, hence the platform toolset must also start with `LLVM-vs...` to ensure the correct MSVC-internally provided configuration with the LLVM/Clang integration.

### CODE REVIEW

**Comment by ldionne** [comment]
For reference, this pull-request is related to issue #201.

**Comment by ldionne** [comment]
Once this passes, could you please squash the three first commits together (since they are just reworks one of another), and I'll merge this.

**Comment by ldionne** [comment]
Oh yes, and if you could rebase on top of the current `develop` branch, it would be really nice.

**Comment by m-j-w** [comment]
Hmm, that didn't work as expected...

**Comment by ldionne** [comment]
If the shit hits the fan, just leave the commits as-is and I'll squash + rebase them as needed :-)

**Comment by m-j-w** [comment]
Well, I should clean that up later. At some point I managed to push my squashed changes to my develop branch.
So just take that squashed commit db9daa69aff2c17cf37841f8d3b38644434cdfc0 on my develop branch. It should merge with your develop branch.

**Comment by ldionne** [comment]
> Well, I should clean that up later. At some point I managed to push my squashed changes to my develop branch.

You want to push to your `windows_build` branch, not your `develop` branch. Pushing to your `windows_build` branch will update this pull request.

**Comment by m-j-w** [comment]
Yeah, well, adding the + sign before the branch to enforce the push after squashing also helps a lot...

**Comment by ldionne** [comment]
> Yeah, well, adding the + sign before the branch to enforce the push after squashing also helps a lot...

You can also use `git push -f` or `git push --force`

**Pull request closed without merging**
